import Head from 'next/head'
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>✗𝙤</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <menu className="py-10 text-white text-center capitalize">
          <h1 className="text-7xl">✗𝙤</h1>
          <h1 className="text-3xl font-bold">A Starboy Diary</h1>
          <h2 className="text-xl">A collection of my favorite music artists</h2>
        </menu>
        <main>
          <div className="p-4 sm:p-20 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
            <img
              src="/images/the-weeknd.jpeg"
              alt="The Weeknd"
              title="The Weeknd"
              className="object-cover w-full h-96"
            />
            <img
              src="/images/asap.jpg"
              alt="Asap Rocky"
              title="Asap Rocky"
              className="object-cover w-full h-96"
            />
            <img
              src="/images/tyler.jpg"
              alt="Tyler, The Creator"
              title="Tyler, The Creator"
              className="object-cover w-full h-96"
            />
            <img
              src="/images/jcole.webp"
              alt="J. Cole"
              title="J. Cole"
              className="object-cover w-full h-96"
            />
            <img
              src="/images/laflame.jpeg"
              alt="Travis Scott"
              title="Travis Scott"
              className="object-cover w-full h-96"
            />
            <img
              src="/images/big-sean.jpg"
              alt="Big Sean"
              title="Big Sean"
              className="object-cover w-full h-96"
            />
          </div>
        </main>
      </section>
    </>
  );
}
